# Generated by Django 3.2.20 on 2023-08-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tersor', '0003_auto_20230810_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
