# Generated by Django 3.2.20 on 2023-08-14 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tersor', '0004_model_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='content',
        ),
        migrations.RemoveField(
            model_name='model',
            name='imagebox',
        ),
        migrations.RemoveField(
            model_name='model',
            name='inputbox',
        ),
        migrations.RemoveField(
            model_name='model',
            name='public',
        ),
        migrations.AddField(
            model_name='model',
            name='apiName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('api_id', models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.CASCADE, related_name='model', to='tersor.model')),
            ],
        ),
    ]
