# Generated by Django 3.2.20 on 2023-08-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tersor', '0005_auto_20230814_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ten',
        ),
    ]
