# Generated by Django 3.2.20 on 2023-08-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tersor', '0007_remove_input_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='api_id',
            field=models.ForeignKey(db_column='api_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='tersor.model'),
        ),
    ]
