# Generated by Django 3.2.20 on 2023-08-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tersor', '0010_alter_model_apiname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='apiName',
            field=models.SlugField(allow_unicode=True, null=True, unique=True),
        ),
    ]
